%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
dataset_dir: /Users/lipenghua/Doc/developer/rgbd_dataset/rgbd_dataset_freiburg1_room/
# camera intrinsics
# fr1
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7

# fr2
#camera.fx: 520.9
#camera.fy: 521.0
#camera.cx: 325.1
#camera.cy: 249.7

camera.depth_scale: 0.0002

# VO Parameters
min_depth: 0.0 # all in meters
max_depth: 4.0
max_depth_diff: 0.07
max_point_ratio: 0.09
max_translation: 0.15
max_rotation: 15 # degrees
